version: '2'

services:
  mariadb-master:
    image: mariadb
    ports:
      - "33060:3306"
    volumes:
      - /srv/mariadb/master/data:/var/lib/mysql
      - /srv/mariadb/master/conf.d:/etc/mysql/conf.d
      - /srv/mariadb/master/entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./master.cnf:/etc/mysql/conf.d/master.cnf:ro
      - ./setup-replication.sql:/docker-entrypoint-initdb.d/setup-replication.sql:ro
    networks:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"

  mariadb-slave1:
    image: mariadb
    ports:
      - "33061:3306"
    volumes:
      - /srv/mariadb/slave/1/data:/var/lib/mysql
      - /srv/mariadb/slave/1/conf.d:/etc/mysql/conf.d
      - /srv/mariadb/slave/entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./start-replication.sql:/start-replication.sql:ro
      - ./slave1.cnf:/etc/mysql/conf.d/slave1.cnf:ro
    links:
      - mariadb-master
    depends_on:
      - mariadb-master
    networks:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"

networks:
  mariadb:
    driver: bridge
