version: '2'

services:
  scylladb-1:
    image: scylladb/scylla
    container_name: scylladb-1
    ports:
      - 7000
      - "10000:10000"
      - "9161:9160"
      - "9042:9042"
    volumes:
      - "/srv/scylladb/1:/var/lib/scylla"
    networks:
      scyllanw:
        ipv4_address: 172.25.0.10
    restart: always

  scylladb-2:
    image: scylladb/scylla
    container_name: scylladb-2
    entrypoint:
      - "/docker-entrypoint.py"
      - "--seeds"
      - "172.25.0.10"
    ports:
      - 7000
      - "9162:9160"
      - "9043:9042"
    links:
      - scylladb-1
    depends_on:
      - scylladb-1
    volumes:
      - "/srv/scylladb/2:/var/lib/scylla"
    networks:
      scyllanw:
        ipv4_address: 172.25.0.20
    restart: always

  scylladb-3:
    image: scylladb/scylla
    container_name: scylladb-3
    entrypoint:
      - "/docker-entrypoint.py"
      - "--seeds"
      - "172.25.0.10"
    ports:
      - 7000
      - "9163:9160"
      - "9044:9042"
    links:
      - scylladb-1
    depends_on:
      - scylladb-1
    volumes:
      - "/srv/scylladb/3:/var/lib/scylla"
    networks:
      scyllanw:
        ipv4_address: 172.25.0.30
    restart: always

networks:
  scyllanw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
