version: '2'

services:
  cassandra-1:
    image: cassandra
    container_name: cassandra-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
    ports:
      - 7000
      - "9161:9160"
      - "9042:9042"
    volumes:
      - "/srv/cassandra/1:/var/lib/cassandra"
    networks:
      - cassandra
    restart: always

  cassandra-2:
    image: cassandra
    container_name: cassandra-2
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-2"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
      - 7000
      - "9162:9160"
      - "9043:9042"
    depends_on:
      - cassandra-1
    volumes:
      - "/srv/cassandra/2:/var/lib/cassandra"
    networks:
      - cassandra
    restart: always

  cassandra-3:
    image: cassandra
    container_name: cassandra-3
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-3"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
      - 7000
      - "9163:9160"
      - "9044:9042"
    depends_on:
      - cassandra-2
    volumes:
      - "/srv/cassandra/3:/var/lib/cassandra"
    networks:
      - cassandra
    restart: always

networks:
  cassandra:
    driver: bridge

