version: '2'

services:
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    volumes:
      - /srv/influxdb/data:/var/lib/influxdb
    networks:
      - influx
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"

  chronograf:
    image: chronograf
    ports:
      - "10000:10000"
    volumes:
      - /srv/chronograf/data:/var/lib/chronograf
    networks:
      - influx
    links:
      - influxdb

  kapacitor:
    image: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - /srv/kapacitor/data:/var/lib/kapacitor
    networks:
      - influx
    links:
      - influxdb
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: "http://influxdb:8086"

  telegraf:
    image: telegraf
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influx
    links:
      - influxdb

networks:
  influx:
    driver: bridge
